# -----------------------------------------------------------------
#                 ROUTING FOR TWIG TEMPLATE
# -----------------------------------------------------------------

route1:
  path:       /eleves/index
  controller: Bundles\AcmeBundle\Controller\AcmeController::index
  methods:    GET

route3:
  path:       /AppController/index/{year}
  controller: Bundles\AppBundle\Controller\AppController::index
  defaults:
    year: 1
  requirements:
    year: '\d+'
  methods:    GET

ajax:
  path:       /eleves/ajax
  controller: Bundles\AcmeBundle\Controller\AcmeController::ajax
  methods:    GET

# -----------------------------------------------------------------
#                 ROUTING FOR PHP TEMPLATE
# -----------------------------------------------------------------
route4:
  path:       /AppController/php/{max}
  controller: Bundles\AppBundle\Controller\AppController::php
  methods:    GET
